-- Config Neovim Minimaliste
require("config.options")
require("config.icons")
require("config.highlights")
require("config.autopairs")
require("config.keyhint")
require("config.snippets").setup()
require("config.lazy")
require("config.lsp")
require("config.statusline").setup()
