local function apply_minimal_highlights()
  local set_hl = vim.api.nvim_set_hl
  vim.o.background = "dark"

  local palette = {
    bg = "#1a1b26",
    bg_alt = "#1f2335",
    bg_alt2 = "#292e42",
    fg = "#d0e7da",
    fg_dim = "#b3ddcd",
    fg_muted = "#90b7cf",
    fg_unused = "#6b7280",
    fg_bright = "#ffffff",
    blue = "#7c9acc",
    blue2 = "#90b7cf",
    blue3 = "#b3ddcd",
    cyan = "#b3ddcd",
    green = "#d0e7da",
    yellow = "#e0af68",
    orange = "#ff9e64",
    red = "#f7768e",
    purple = "#e8bed3",
    magenta = "#e8bed3",
  }

  local c = palette

  set_hl(0, "Normal", { fg = c.fg, bg = c.bg })
  set_hl(0, "NormalNC", { fg = c.fg, bg = c.bg })
  set_hl(0, "NormalFloat", { fg = c.fg, bg = c.bg_alt })
  set_hl(0, "FloatBorder", { fg = c.blue, bg = c.bg_alt })
  set_hl(0, "FloatTitle", { fg = c.magenta, bg = c.bg_alt, bold = true })
  set_hl(0, "ColorColumn", { bg = c.bg_alt })
  set_hl(0, "CursorLine", { bg = c.bg_alt })
  set_hl(0, "CursorLineNr", { fg = c.blue2, bg = c.bg_alt, bold = true })
  set_hl(0, "LineNr", { fg = c.fg_muted })
  set_hl(0, "SignColumn", { bg = c.bg })
  set_hl(0, "CursorLineSign", { bg = c.bg_alt })
  set_hl(0, "CursorLineFold", { bg = c.bg_alt })
  set_hl(0, "WinSeparator", { fg = c.bg_alt2, bg = c.bg })
  set_hl(0, "VertSplit", { fg = c.bg_alt2, bg = c.bg })
  set_hl(0, "StatusLine", { fg = c.fg, bg = c.bg_alt2 })
  set_hl(0, "StatusLineNC", { fg = c.fg_dim, bg = c.bg_alt })
  set_hl(0, "TabLine", { fg = c.fg_dim, bg = c.bg_alt })
  set_hl(0, "TabLineSel", { fg = c.fg, bg = c.bg_alt2, bold = true })
  set_hl(0, "TabLineFill", { bg = c.bg })
  set_hl(0, "Pmenu", { fg = c.fg, bg = c.bg_alt })
  set_hl(0, "PmenuSel", { fg = c.bg, bg = c.purple, bold = true })
  set_hl(0, "PmenuSbar", { bg = c.bg_alt2 })
  set_hl(0, "PmenuThumb", { bg = c.blue })
  set_hl(0, "Visual", { bg = c.bg_alt2 })
  set_hl(0, "Search", { fg = c.bg, bg = c.purple })
  set_hl(0, "IncSearch", { fg = c.bg, bg = c.magenta })
  set_hl(0, "MatchParen", { fg = c.magenta, bg = c.bg_alt2, bold = true })
  set_hl(0, "Folded", { fg = c.fg_dim, bg = c.bg_alt })
  set_hl(0, "NonText", { fg = c.bg_alt2 })
  set_hl(0, "EndOfBuffer", { fg = c.bg })
  set_hl(0, "Whitespace", { fg = c.bg_alt2 })
  set_hl(0, "Title", { fg = c.magenta, bold = true })
  set_hl(0, "Directory", { fg = c.blue2 })

  set_hl(0, "NetrwNormal", { fg = c.fg_dim, bg = c.bg_alt2 })
  set_hl(0, "NetrwLineNr", { fg = c.fg_muted, bg = c.bg_alt2 })
  set_hl(0, "NetrwSignColumn", { bg = c.bg_alt2 })
  set_hl(0, "NetrwCursorLine", { bg = c.bg_alt })
  set_hl(0, "NetrwCursorLineNr", { fg = c.orange, bg = c.bg_alt, bold = true })
  set_hl(0, "NetrwTreeBar", { fg = c.bg })
  set_hl(0, "NetrwClassify", { fg = c.orange })
  set_hl(0, "NetrwDir", { fg = c.blue2, bold = true })
  set_hl(0, "NetrwExe", { fg = c.green, bold = true })
  set_hl(0, "NetrwLink", { fg = c.cyan, underline = true })
  set_hl(0, "NetrwPlain", { fg = c.fg_dim })
  set_hl(0, "NetrwSignDir", { fg = c.blue2, bg = c.bg_alt })
  set_hl(0, "NetrwSignFile", { fg = c.fg_muted, bg = c.bg_alt })
  set_hl(0, "NetrwSignLink", { fg = c.cyan, bg = c.bg_alt })

  set_hl(0, "netrwDir", { link = "NetrwDir" })
  set_hl(0, "netrwClassify", { link = "NetrwClassify" })
  set_hl(0, "netrwTreeBar", { link = "NetrwTreeBar" })
  set_hl(0, "netrwExe", { link = "NetrwExe" })
  set_hl(0, "netrwLink", { link = "NetrwLink" })
  set_hl(0, "netrwSymLink", { link = "NetrwLink" })
  set_hl(0, "netrwPlain", { link = "NetrwPlain" })
  set_hl(0, "netrwList", { link = "NetrwPlain" })
  set_hl(0, "netrwComment", { link = "Comment" })

  set_hl(0, "SnacksPickerFile", { fg = c.fg_bright })
  set_hl(0, "SnacksPickerDirectory", { fg = c.fg_bright })
  set_hl(0, "SnacksPickerDir", { fg = c.fg_bright })
  set_hl(0, "SnacksPickerPathHidden", { fg = c.fg_bright })
  set_hl(0, "SnacksPickerPathIgnored", { fg = c.fg_bright })

  set_hl(0, "Comment", { fg = c.fg_muted, italic = true })
  set_hl(0, "Constant", { fg = c.magenta })
  set_hl(0, "String", { fg = c.blue3 })
  set_hl(0, "Character", { fg = c.blue3 })
  set_hl(0, "Number", { fg = c.orange })
  set_hl(0, "Boolean", { fg = c.orange })
  set_hl(0, "Identifier", { fg = c.fg })
  set_hl(0, "Function", { fg = c.blue })
  set_hl(0, "Statement", { fg = c.purple })
  set_hl(0, "Keyword", { fg = c.purple })
  set_hl(0, "Conditional", { fg = c.purple })
  set_hl(0, "Repeat", { fg = c.purple })
  set_hl(0, "Operator", { fg = c.blue2 })
  set_hl(0, "Type", { fg = c.cyan })
  set_hl(0, "PreProc", { fg = c.magenta })
  set_hl(0, "Special", { fg = c.blue2 })
  set_hl(0, "Todo", { fg = c.bg, bg = c.magenta, bold = true })

  set_hl(0, "Include", { fg = c.cyan })
  set_hl(0, "@keyword.import", { link = "Include" })
  set_hl(0, "@keyword.import.python", { link = "Include" })
  set_hl(0, "@include", { link = "Include" })
  set_hl(0, "@include.python", { link = "Include" })

  set_hl(0, "@module", { fg = c.blue2 })
  set_hl(0, "@module.python", { link = "@module" })
  set_hl(0, "@namespace", { fg = c.blue2 })
  set_hl(0, "@namespace.python", { link = "@namespace" })

  set_hl(0, "TSInclude", { link = "Include" })
  set_hl(0, "pythonImport", { link = "Include" })
  set_hl(0, "pythonFromImport", { link = "Include" })
  set_hl(0, "pythonImportedAs", { link = "Include" })

  set_hl(0, "@comment", { link = "Comment" })
  set_hl(0, "@constant", { link = "Constant" })
  set_hl(0, "@constant.builtin", { link = "Constant" })
  set_hl(0, "@constant.macro", { link = "PreProc" })
  set_hl(0, "@string", { link = "String" })
  set_hl(0, "@string.special", { fg = c.blue3 })
  set_hl(0, "@string.escape", { fg = c.magenta })
  set_hl(0, "@string.regex", { fg = c.purple })
  set_hl(0, "@number", { link = "Number" })
  set_hl(0, "@boolean", { link = "Boolean" })
  set_hl(0, "@function", { link = "Function" })
  set_hl(0, "@function.builtin", { fg = c.blue2 })
  set_hl(0, "@function.method", { link = "Function" })
  set_hl(0, "@constructor", { fg = c.blue2 })
  set_hl(0, "@method", { link = "Function" })
  set_hl(0, "@type", { link = "Type" })
  set_hl(0, "@type.builtin", { link = "Type" })
  set_hl(0, "@type.qualifier", { link = "Keyword" })
  set_hl(0, "@storageclass", { link = "Keyword" })
  set_hl(0, "@variable", { link = "Identifier" })
  set_hl(0, "@variable.builtin", { fg = c.magenta })
  set_hl(0, "@variable.member", { fg = c.blue2 })
  set_hl(0, "@property", { fg = c.blue2 })
  set_hl(0, "@field", { fg = c.blue2 })
  set_hl(0, "@parameter", { fg = c.fg })
  set_hl(0, "@operator", { link = "Operator" })
  set_hl(0, "@punctuation.delimiter", { fg = c.fg_dim })
  set_hl(0, "@punctuation.bracket", { fg = c.fg_dim })
  set_hl(0, "@punctuation.special", { fg = c.purple })
  set_hl(0, "@keyword", { link = "Keyword" })
  set_hl(0, "@keyword.function", { link = "Keyword" })
  set_hl(0, "@keyword.operator", { link = "Operator" })
  set_hl(0, "@keyword.return", { link = "Keyword" })
  set_hl(0, "@keyword.conditional", { link = "Conditional" })
  set_hl(0, "@keyword.repeat", { link = "Repeat" })
  set_hl(0, "@keyword.exception", { link = "Keyword" })
  set_hl(0, "@keyword.directive", { link = "PreProc" })
  set_hl(0, "@keyword.directive.define", { link = "PreProc" })
  set_hl(0, "@label", { link = "Keyword" })
  set_hl(0, "@attribute", { fg = c.magenta })

  set_hl(0, "@lsp.mod.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.variable.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.parameter.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.property.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.namespace.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.module.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.function.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.method.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.class.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.enumMember.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "@lsp.typemod.typeAlias.unused", { fg = c.fg_unused, italic = true })
  set_hl(0, "LspInlayHint", { fg = c.fg_muted, bg = c.bg_alt })

  set_hl(0, "DiagnosticError", { fg = c.red })
  set_hl(0, "DiagnosticWarn", { fg = c.yellow })
  set_hl(0, "DiagnosticInfo", { fg = c.blue })
  set_hl(0, "DiagnosticHint", { fg = c.cyan })
  set_hl(0, "DiagnosticSignError", { fg = c.red, bg = c.bg })
  set_hl(0, "DiagnosticSignWarn", { fg = c.yellow, bg = c.bg })
  set_hl(0, "DiagnosticSignInfo", { fg = c.blue, bg = c.bg })
  set_hl(0, "DiagnosticSignHint", { fg = c.cyan, bg = c.bg })
  set_hl(0, "DiagnosticFloatingError", { fg = c.red, bg = c.bg_alt })
  set_hl(0, "DiagnosticFloatingWarn", { fg = c.yellow, bg = c.bg_alt })
  set_hl(0, "DiagnosticFloatingInfo", { fg = c.blue, bg = c.bg_alt })
  set_hl(0, "DiagnosticFloatingHint", { fg = c.cyan, bg = c.bg_alt })
  set_hl(0, "DiagnosticUnnecessary", { fg = c.fg_unused, italic = true })
  set_hl(0, "DiagnosticDeprecated", { fg = c.fg_unused, strikethrough = true })
  set_hl(0, "DiagnosticVirtualTextError", { fg = c.red, bg = c.bg_alt })
  set_hl(0, "DiagnosticVirtualTextWarn", { fg = c.yellow, bg = c.bg_alt })
  set_hl(0, "DiagnosticVirtualTextInfo", { fg = c.blue, bg = c.bg_alt })
  set_hl(0, "DiagnosticVirtualTextHint", { fg = c.cyan, bg = c.bg_alt })
  set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.red })
  set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.yellow })
  set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = c.blue })
  set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = c.cyan })
  set_hl(0, "DiagnosticUnderlineUnnecessary", { undercurl = true, sp = c.fg_muted })
  set_hl(0, "DiagnosticUnderlineDeprecated", { undercurl = true, sp = c.fg_muted })
  set_hl(0, "LspReferenceText", { bg = c.bg_alt2 })
  set_hl(0, "LspReferenceRead", { bg = c.bg_alt2 })
  set_hl(0, "LspReferenceWrite", { bg = c.bg_alt2 })

  set_hl(0, "DiffAdd", { fg = c.green, bg = c.bg_alt })
  set_hl(0, "DiffChange", { fg = c.blue, bg = c.bg_alt })
  set_hl(0, "DiffDelete", { fg = c.red, bg = c.bg_alt })
  set_hl(0, "DiffText", { fg = c.blue2, bg = c.bg_alt2, bold = true })
end

apply_minimal_highlights()

vim.api.nvim_create_autocmd("ColorScheme", {
  callback = apply_minimal_highlights,
})
